version: "3.9"
services:
  db:
    container_name: meu_pet_db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: meu_pet
      MYSQL_USER: pet
      MYSQL_PASSWORD: pet
    volumes:
      - /scripts/mysql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uexample -pexample"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "3306:3306"