// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"github.com/MrHenri/meuPet/internal/entities"
	"github.com/MrHenri/meuPet/internal/events"
	"github.com/MrHenri/meuPet/internal/infra/database"
	"github.com/MrHenri/meuPet/internal/usecase"
	events2 "github.com/MrHenri/meuPet/pkg/events"
	"github.com/google/wire"
)

// Injectors from wire.go:

func NewUserUseCase(db *sql.DB) *usecase.UserUseCase {
	userRepository := database.NewUserRepository(db)
	userUseCase := usecase.NewUserUseCase(userRepository)
	return userUseCase
}

// wire.go:

var setUserRepositoryDependency = wire.NewSet(database.NewUserRepository, wire.Bind(new(entities.UserRepositoryInterface), new(*database.UserRepository)))

var setUserEventDependency = wire.NewSet(events.NewUserEvent, wire.Bind(new(events2.EventInterface), new(*events.UserEvent)))

var setEventDispatcherDependency = wire.NewSet(events2.NewEventDispatcher, events.NewUserEvent, wire.Bind(new(events2.EventDispatcherInterface), new(*events2.EventDispatcher)), wire.Bind(new(events2.EventInterface), new(*events.UserEvent)))
